import Head from "next/head";
import Image from "next/image";
import LoadingComponent from "../components/LoadingComponent";
import styles from "../styles/Home.module.css";
import useDeviceFetch from "./useDeviceFetch";

export default function Home() {
  const { loading, devices, toggleDevice, getDevices } = useDeviceFetch();
  return loading ? (
    <LoadingComponent />
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hola <a href="https://nextjs.org">Chiquitolina</a>
        </h1>

        <p className={styles.description}>
          Aqui puedes gestionar el router{" "}
          <code className={styles.code}>(sacar a los fastidiosos xD)</code>
        </p>

        <div className={styles.grid}>
          {devices.map((device) => (
            <a
              onClick={(e) => {
                e.preventDefault();
                toggleDevice(device);
              }}
              className={styles.card}
            >
              <h2>{device.name}</h2>
              <p>{device.enable ? "Is active" : "Is not active"}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
