import Head from "next/head";
import { useState } from "react";
import DeviceCard from "../components/DeviceCard/DeviceCard";
import { Insights } from "../components/Insights/Insights";
import s from "../styles/Home.module.scss";
import useDeviceFetch from "./useDeviceFetch";

export default function Home() {
  const { loading, devices, toggleDevice, getDevices } = useDeviceFetch();
  const [macSelected, setSelected] = useState("");

  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <section className={s.header}>
          <h1 className={s.title}>Dispositivos</h1>
        </section>
        <section className={s.insights}>
          <Insights devices={devices} />
        </section>
        <section className={`${s.noPadding} ${s.devicesContainer}`}>
          {devices.map((device) => (
            <DeviceCard
              device={device}
              isSelected={device.mac === macSelected}
              onToggleDevice={toggleDevice}
              onSelect={setSelected}
            />
          ))}
        </section>
      </main>
    </div>
  );
}
